# Use postgres/example user/password credentials
# ERRO DO POSTGRES ADMINER
# https://medium.com/@vinjenks/dockerized-local-postgres-and-scram-authentication-a-quick-fix-21c432951bd

version: '3.1'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    #volumes:
    #  - "/db_data:/var/lib/postgresql/data"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  api:
    #container_name: api_1
    environment:
      # postgres://<user>:<password>@<url>:<port>/<database>
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432"
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    depends_on:
      - api

  web_app:
    build:
      context: ./web_app
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - nginx
  